language: javascript
install:
  - cd $TRAVIS_BUILD_DIR/app && npm i -f --loglevel=warning
script:
  - cd $TRAVIS_BUILD_DIR/app && npm run build
  - cd $TRAVIS_BUILD_DIR/app && npm run test
  - bash $TRAVIS_BUILD_DIR/scripts/rename-build-file.sh